Repository enso-org/ide, pull requests merged in 2019-11, with the labels that each got.

#39 Add msdfgen-sys crate
  .github/workflows/build.yml
  .gitignore
  Cargo.toml
  README.md
  lib/core/msdf-sys/Cargo.toml
  lib/core/msdf-sys/build.rs
  lib/core/msdf-sys/src/internal.rs
  lib/core/msdf-sys/src/lib.rs
Labels: Category: Renderer, Change: Non-Breaking, Difficulty: Hard, Priority: High, Type: Enhancement

#48 HTML Rendering System
  lib/core/Cargo.toml
  lib/core/src/data/mod.rs
  lib/core/src/data/opt_vec.rs
  lib/core/src/data/types.rs
  lib/core/src/display/mod.rs
  lib/core/src/display/rendering/camera.rs
  lib/core/src/display/rendering/htmlobject.rs
  lib/core/src/display/rendering/htmlrenderer.rs
  lib/core/src/display/rendering/htmlscene.rs
  lib/core/src/display/rendering/mod.rs
  lib/core/src/display/rendering/object.rs
  lib/core/src/display/rendering/renderer.rs
  lib/core/src/display/rendering/scene.rs
  lib/core/src/display/rendering/transform.rs
  lib/core/src/display/world.rs
  lib/core/src/lib.rs
  lib/core/src/math/mod.rs
  lib/core/src/math/utils.rs
  lib/core/tests/common.rs
  lib/core/tests/htmlrenderer.rs
  lib/prelude/Cargo.toml
  lib/prelude/src/lib.rs
  lib/system/web/src/lib.rs
Labels: Category: API, Category: Renderer, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#49 Add wasm-pack test to github workflows
  .github/workflows/build.yml
  .gitignore
  lib/system/web/Cargo.toml
  script/rust/Cargo.toml
  script/rust/src/bin/test-all.rs
  script/test.sh
Labels: Category: External, Change: Non-Breaking, Difficulty: Beginner, Priority: Medium, Type: Bug
