Repository enso-org/ide, pull requests merged in 2019-12, with the labels that each got.

#62 Text display: letters alignment
  build-utilities/src/lib.rs
  examples/03-text/.gitignore
  lib/core/Cargo.toml
  lib/core/embedded-fonts/build.rs
  lib/core/embedded-fonts/src/lib.rs
  lib/core/msdf-sys/Cargo.toml
  lib/core/msdf-sys/build.rs
  lib/core/msdf-sys/src/emscripten_data.rs
  lib/core/msdf-sys/src/internal.rs
  lib/core/msdf-sys/src/lib.rs
  lib/core/msdf-sys/src/test_utils.rs
  lib/core/src/data/container.rs
  lib/core/src/data/opt_vec.rs
  lib/core/src/lib.rs
  lib/core/src/text.rs
  lib/core/src/text/font.rs
  lib/core/src/text/glyph_render.rs
  lib/core/src/text/mod.rs
  lib/core/src/text/msdf.rs
  lib/core/src/text/msdf_frag.glsl
  lib/core/src/text/msdf_vert.glsl
  lib/prelude/Cargo.toml
  lib/prelude/src/lib.rs
  lib/system/web/js/resize_observer.js
Labels: Category: Renderer, Change: Non-Breaking, Difficulty: Hard, Priority: High, Type: Enhancement

#67 Implemented newlines
  lib/core/src/lib.rs
  lib/core/src/text.rs
  lib/core/src/text/buffer.rs
  lib/core/src/text/buffer/glyph_square.rs
  lib/core/src/text/buffer/line.rs
  lib/prelude/Cargo.toml
  lib/prelude/src/lib.rs
Labels: Category: Renderer, Change: Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#75 Text clipping
  lib/core/src/lib.rs
  lib/core/src/text.rs
  lib/core/src/text/buffer.rs
  lib/core/src/text/buffer/fragment.rs
  lib/core/src/text/buffer/glyph_square.rs
  lib/core/src/text/msdf_frag.glsl
  lib/core/src/text/msdf_vert.glsl
Labels: Category: Renderer, Change: Breaking, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#84 Text scrolling
  README.md
  lib/core/build.rs
  lib/core/embedded-fonts/src/lib.rs
  lib/core/msdf-sys/src/lib.rs
  lib/core/src/display/workspace.rs
  lib/core/src/display/world.rs
  lib/core/src/lib.rs
  lib/core/src/text.rs
  lib/core/src/text/buffer.rs
  lib/core/src/text/buffer/fragment.rs
  lib/core/src/text/buffer/glyph_square.rs
  lib/core/src/text/buffer/line.rs
  lib/core/src/text/font.rs
  lib/core/src/text/msdf.rs
  lib/core/src/text/msdf_frag.glsl
  lib/core/src/text/msdf_vert.glsl
  lib/core/tests/text.rs
  lib/system/web/src/lib.rs
  lib/web-test/src/bencher.rs
Labels: Category: API, Category: Renderer, Change: Breaking, Difficulty: Hard, Priority: Highest, Type: Enhancement

#88 Text editing
  lib/core/src/text.rs
  lib/core/src/text/buffer.rs
  lib/core/src/text/buffer/fragment.rs
  lib/core/src/text/buffer/glyph_square.rs
  lib/core/src/text/content.rs
  lib/core/src/text/msdf_vert.glsl
  lib/core/tests/text.rs
Labels: Category: API, Category: Renderer, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#91 60 steps per second Physics Simulator (Kinematics, Spring, Air Dragging)
  lib/core/src/animation.rs
  lib/core/src/animation/animator.rs
  lib/core/src/animation/continuous_time_animator.rs
  lib/core/src/animation/fixed_step_animator.rs
  lib/core/src/animation/mod.rs
  lib/core/src/animation/physics.rs
  lib/core/src/control/event_loop.rs
  lib/core/src/display/render/css3d/html/html_object.rs
  lib/core/src/display/render/css3d/html/html_renderer.rs
  lib/core/src/display/render/css3d/object.rs
  lib/core/src/display/render/css3d/scene.rs
  lib/core/src/display/render/css3d/transform.rs
  lib/core/src/lib.rs
  lib/core/src/traits.rs
  lib/core/tests/html_renderer.rs
  lib/core/tests/physics_simulator.rs
  lib/system/web/src/animation_frame_loop.rs
  lib/system/web/src/lib.rs
  lib/web-test/src/bencher.rs
Labels: Category: API, Category: Performance, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement
