Repository enso-org/ide, pull requests merged in 2020-12, with the labels that each got.

#1007 Allow visualizations to consume bare vectors
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/histogram.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js
Labels: Category: GUI, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1001 Only prevent default zooming when holding ctrl key.
  build/run.js
  src/rust/ensogl/lib/core/src/display/navigation/navigator.rs
  src/rust/ensogl/lib/core/src/display/navigation/navigator/events.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/src/documentation.rs
  src/rust/ide/view/src/project.rs
  src/rust/ide/view/src/searcher.rs
Labels: Category: GUI, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Bug

#1015 Set a node's position to the default value in the metadata if there is not any.
  src/rust/ide/src/view/integration.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Bug

#1032 Install missing components of Engine
  docs/CONTRIBUTING.md
  src/rust/ide/lib/enso-protocol/src/project_manager.rs
  src/rust/ide/src/controller/graph/executed.rs
  src/rust/ide/src/ide.rs
  src/rust/ide/tests/project_manager.rs
Labels: Category: Controllers, Difficulty: Hard, Priority: Highest, Type: Enhancement

#1014 Avoid changing edit status of project name when selecting it
  src/rust/ide/view/graph-editor/src/component/breadcrumbs/project_name.rs
Labels: Category: GUI, Good First Issue, Priority: High, Type: Bug

#1037 Increase PM timeout
  src/rust/ide/src/ide.rs
Labels: Category: Controllers, Difficulty: Intermediate, Priority: Highest, Type: Bug

#1033 Avoid updating positions of nodes during type updates.
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/graph/executed.rs
  src/rust/ide/src/view/integration.rs
Labels: Category: Controllers, Category: GUI, Priority: High, Type: Bug

#1043 Optimised engine updates
  src/rust/ide/lib/enso-protocol/src/language_server/types.rs
  src/rust/ide/lib/utils/src/lib.rs
  src/rust/ide/lib/utils/src/string.rs
  src/rust/ide/src/model/module/synchronized.rs
Labels: Category: Controllers, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1057 Avoid changing edit status of project name when selecting it
  src/rust/ide/view/graph-editor/src/component/breadcrumbs/project_name.rs
Labels: Category: GUI, Difficulty: Intermediate, Priority: High, Type: Bug

#1058 Examples in Searcher
  build/run.js
  src/rust/ide/lib/ast/impl/src/lib.rs
  src/rust/ide/lib/ast/impl/src/opr.rs
  src/rust/ide/lib/ast/impl/src/prefix.rs
  src/rust/ide/lib/enso-protocol/src/project_manager.rs
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/searcher.rs
  src/rust/ide/src/controller/searcher/action.rs
  src/rust/ide/src/double_representation/definition.rs
  src/rust/ide/src/double_representation/module.rs
  src/rust/ide/src/model/module/synchronized.rs
  src/rust/ide/src/model/suggestion_database.rs
  src/rust/ide/src/model/suggestion_database/entry.rs
  src/rust/ide/src/model/suggestion_database/example.rs
  src/rust/ide/src/test.rs
  src/rust/ide/src/tests.rs
  src/rust/ide/src/view/integration.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/src/project.rs
  src/rust/ide/view/src/searcher.rs
Labels: Category: Controllers, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1018 Geo_Point popup on hover in Geo_Maps.
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/geoMap.js
  src/rust/ide/view/src/project.rs
Labels: Category: Controllers, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1082 fix: Update edges on node expression updates.
  src/rust/ide/src/view/integration.rs
Labels: Category: Controllers, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1081 Add option for connecting to Language Server directly
  src/rust/ide/lib/enso-protocol/src/project_manager.rs
  src/rust/ide/src/config.rs
  src/rust/ide/src/ide.rs
  src/rust/ide/src/ide/initializer.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/src/lib.rs
  src/rust/ide/src/model/project/synchronized.rs
  src/rust/ide/src/tests.rs
  src/rust/ide/src/transport/web.rs
  src/rust/ide/src/view.rs
  src/rust/ide/tests/language_server.rs
  src/rust/ide/tests/project_manager.rs
  src/rust/lib/system/web/src/lib.rs
Labels: Category: Controllers, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1079 Errors on nodes
  build/run.js
  src/rust/ensogl/lib/core/src/display/shape/primitive/def/class.rs
  src/rust/ensogl/lib/core/src/display/shape/primitive/def/modifier.rs
  src/rust/ensogl/lib/core/src/display/shape/primitive/glsl/shape.glsl
  src/rust/ensogl/lib/core/src/display/shape/primitive/shader/canvas.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/node/error.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/src/debug_scenes/interface.rs
Labels: Category: GUI, Difficulty: Hard, Priority: High, Type: Enhancement

#1070 Bundle project manager in electron package.
  .github/workflows/build.yml
  build/paths.js
  build/run.js
  src/js/lib/client/package.js
  src/js/lib/client/src/index.js
  src/js/lib/project-manager/package.js
  src/js/lib/project-manager/src/build.ts
  src/js/package-lock.json
Labels: Category: Controllers, Category: GUI, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1077 Fixing "Improper behavior while trying to reconnect node with arguments"
  src/rust/Cargo.lock
  src/rust/ensogl/example/Cargo.toml
  src/rust/ensogl/lib/components/Cargo.toml
  src/rust/ensogl/lib/core/Cargo.toml
  src/rust/ensogl/lib/core/src/data.rs
  src/rust/ensogl/lib/core/src/display/symbol/gpu.rs
  src/rust/ensogl/lib/core/src/system/gpu/data/attribute.rs
  src/rust/ensogl/lib/text/Cargo.toml
  src/rust/ide/Cargo.toml
  src/rust/ide/lib/ast/impl/Cargo.toml
  src/rust/ide/lib/enso-protocol/Cargo.toml
  src/rust/ide/lib/json-rpc/Cargo.toml
  src/rust/ide/lib/parser/Cargo.toml
  src/rust/ide/lib/span-tree/Cargo.toml
  src/rust/ide/lib/utils/Cargo.toml
  src/rust/ide/view/Cargo.toml
  src/rust/ide/view/graph-editor/Cargo.toml
  src/rust/lib/system/web/Cargo.toml
Labels: Category: BaseGL, Difficulty: Core Contributor, Priority: High, Type: Bug

#949 Bump parser - Copy button & fix indentation in Code Block
  src/rust/ide/lib/parser/build.rs
  src/rust/ide/view/src/documentation.rs
  src/rust/ide/view/src/documentation/style.css
Labels: Category: GUI, Difficulty: Intermediate, Priority: High, Type: Enhancement
