Repository enso-org/ide, pull requests merged in 2020-03, with the labels that each got.

#224 Selecting word occurrences
  lib/core/src/display/shape/text/text_field.rs
  lib/core/src/display/shape/text/text_field/content.rs
  lib/core/src/display/shape/text/text_field/cursor.rs
  lib/core/src/display/shape/text/text_field/frp/keyboard.rs
  lib/core/src/display/shape/text/text_field/word_occurrence.rs
  lib/frp/src/io/keyboard.rs
  lib/ide/file-manager/mock-server/.gitignore
  lib/ide/src/view/text_editor.rs
Labels: Category: BaseGL API, Category: IDE, Change: Non-Breaking, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#232 Keep cursor positions on text refresh
  lib/core/src/display/shape/text/text_field.rs
  lib/core/src/display/shape/text/text_field/cursor.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#215 Generate idmap from AST.
  lib/data/src/text.rs
  lib/ide/ast/impl/src/lib.rs
  lib/ide/ast/impl/src/repr.rs
  lib/ide/ast/macros/src/lib.rs
  lib/ide/ast/macros/src/repr.rs
  lib/ide/ast/macros/src/token.rs
  lib/ide/parser/tests/parsing.rs
  lib/ide/parser/tests/web.rs
  lib/shapely/impl/src/shared.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#250 Node Discovery
  lib/ide/ast/impl/src/lib.rs
  lib/ide/parser/build.rs
  lib/ide/parser/tests/web.rs
  lib/ide/src/controller/module.rs
  lib/ide/src/double_representation.rs
  lib/ide/src/double_representation/definition.rs
  lib/ide/src/double_representation/graph.rs
  lib/ide/src/double_representation/node.rs
  lib/ide/src/lib.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#231 Implemented notification about text&graph changes brokering
  Cargo.lock
  docs/contributing.md
  lib/core/src/display/shape/text/text_field.rs
  lib/core/src/display/shape/text/text_field/content.rs
  lib/core/src/display/shape/text/text_field/content/location.rs
  lib/data/src/text.rs
  lib/frp/Cargo.toml
  lib/ide/json-rpc/src/handler.rs
  lib/ide/src/controller.rs
  lib/ide/src/controller/module.rs
  lib/ide/src/controller/notification.rs
  lib/ide/src/controller/project.rs
  lib/ide/src/controller/text.rs
  lib/ide/src/executor.rs
  lib/ide/src/executor/test_utils.rs
  lib/ide/src/transport.rs
  lib/ide/src/transport/test_utils.rs
  lib/ide/src/view/project.rs
  lib/ide/src/view/text_editor.rs
  lib/ide/utils/src/channel.rs
Labels: Category: IDE, Change: Breaking, Difficulty: Intermediate, Priority: High, Type: Enhancement

#237 Metadata storage for module controller.
  lib/ide/ast/impl/src/lib.rs
  lib/ide/parser/build.rs
  lib/ide/parser/src/api.rs
  lib/ide/parser/src/jsclient.rs
  lib/ide/parser/src/lib.rs
  lib/ide/parser/src/wsclient.rs
  lib/ide/parser/tests/parsing.rs
  lib/ide/parser/tests/web.rs
  lib/ide/src/controller/module.rs
  lib/ide/src/double_representation/definition.rs
  lib/ide/src/double_representation/graph.rs
  lib/ide/src/double_representation/text.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#261 Shape now implements Clone and Ast allows setting/removing id.
  lib/ide/ast/impl/src/lib.rs
  lib/ide/ast/macros/src/lib.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Discussion

#265 Fix text selection
  src/js/package-lock.json
  src/rust/ensogl/src/display/object.rs
  src/rust/ensogl/src/display/shape/text/text_field.rs
  src/rust/ensogl/src/display/shape/text/text_field/render.rs
  src/rust/ensogl/src/display/symbol/gpu/geometry/compound/sprite.rs
  src/rust/ide/src/view/text_editor.rs
  src/rust/lib/debug-scenes/src/sprite_system.rs
  src/rust/lib/debug-scenes/src/text_field.rs
  src/rust/lib/debug-scenes/src/text_typing.rs
Labels: Category: BaseGL Renderer, Change: Non-Breaking, Difficulty: Intermediate, Priority: Highest, Type: Bug

#270 Fix stuck keymask after alt-tabbing
  src/rust/ensogl/src/system/web/text_input.rs
  src/rust/ensogl/src/system/web/text_input/text_input.js
  src/rust/lib/frp/src/io/keyboard.rs
Labels: Category: BaseGL API, Change: Breaking, Difficulty: Beginner, Priority: Highest, Type: Bug

#269 Fix build script
  src/rust/ensogl/build.rs
  src/rust/ide/parser/build.rs
Labels: Category: External, Change: Non-Breaking, Difficulty: Beginner, Priority: Low, Type: Bug

#241 Make the extra cursor navigation operations in TextField
  src/rust/ensogl/src/display/shape/text/text_field.rs
  src/rust/ensogl/src/display/shape/text/text_field/content.rs
  src/rust/ensogl/src/display/shape/text/text_field/cursor.rs
  src/rust/ensogl/src/display/shape/text/text_field/frp/keyboard.rs
  src/rust/ensogl/src/display/shape/text/text_field/frp/mouse.rs
  src/rust/ensogl/src/display/shape/text/text_field/word_occurrence.rs
Labels: Category: BaseGL API, Change: Non-Breaking, Difficulty: Intermediate, Priority: Low, Type: Enhancement

#262 Graph and Node controllers stub and mock implementations
  src/rust/ide/ast/impl/src/lib.rs
  src/rust/ide/src/controller.rs
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/module.rs
  src/rust/ide/src/controller/notification.rs
  src/rust/ide/src/controller/project.rs
  src/rust/ide/src/controller/text.rs
  src/rust/ide/src/double_representation/definition.rs
  src/rust/ide/src/double_representation/graph.rs
  src/rust/ide/src/double_representation/node.rs
  src/rust/ide/src/lib.rs
  src/rust/ide/src/view/project.rs
  src/rust/ide/utils/src/fail.rs
  src/rust/ide/utils/src/lib.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#271 Improve cursor blinking
  src/rust/ensogl/src/display/shape/text/text_field/render.rs
Labels: Category: BaseGL Renderer, Change: Non-Breaking, Difficulty: Beginner, Priority: Low, Type: Bug

#276 Removes idmap field from module controller.
  src/rust/ide/src/controller/module.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#273 Mac and Windows shortcuts fixes
  src/rust/ensogl/src/display/shape/text/text_field/frp/keyboard.rs
  src/rust/lib/frp/src/io/keyboard.rs
Labels: Category: BaseGL API, Change: Non-Breaking, Difficulty: Beginner, Priority: High, Type: Bug

#278 Cursor word step tests fix
  src/rust/ensogl/src/display/shape/text/text_field/cursor.rs
Labels: Category: BaseGL API, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Bug

#274 Graph API - Node position in metadata
  src/rust/Cargo.lock
  src/rust/ide/Cargo.toml
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/module.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Intermediate, Priority: Highest

#284 Fix instructions to set up toolchain for project build. Fixes #283.
  docs/contributing.md
Labels: Category: External, Change: Non-Breaking, Difficulty: Beginner, Priority: Medium, Type: Enhancement

#292 Fix drawing instance with empty buffers
  src/rust/ensogl/src/display/symbol/gpu.rs
  src/rust/ensogl/src/system/gpu/data/buffer.rs
Labels: Category: BaseGL Renderer, Change: Non-Breaking, Difficulty: Hard, Priority: Highest, Type: Bug

#291 CI fails on error
  build/cmd.js
  src/rust/ide/ast/impl/src/lib.rs
  src/rust/ide/parser/tests/web.rs
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/module.rs
  src/rust/lib/data/src/text.rs
Labels: Category: External, Change: Non-Breaking, Difficulty: Hard, Priority: Highest, Type: Bug

#298 Node Operations
  src/js/package-lock.json
  src/rust/ide/ast/impl/Cargo.toml
  src/rust/ide/ast/impl/src/crumbs.rs
  src/rust/ide/ast/impl/src/known.rs
  src/rust/ide/ast/impl/src/lib.rs
  src/rust/ide/ast/impl/src/opr.rs
  src/rust/ide/ast/impl/src/repr.rs
  src/rust/ide/ast/impl/src/test_utils.rs
  src/rust/ide/ast/impl/src/traits.rs
  src/rust/ide/parser/src/api.rs
  src/rust/ide/parser/src/lib.rs
  src/rust/ide/parser/src/test_utils.rs
  src/rust/ide/parser/tests/parsing.rs
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/module.rs
  src/rust/ide/src/double_representation.rs
  src/rust/ide/src/double_representation/definition.rs
  src/rust/ide/src/double_representation/graph.rs
  src/rust/ide/src/double_representation/node.rs
  src/rust/ide/src/lib.rs
  src/rust/ide/utils/src/lib.rs
  src/rust/ide/utils/src/test.rs
  src/rust/ide/utils/src/vec.rs
  src/rust/lib/logger/src/lib.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#315 Proc macro for #[derive(CloneRef)]
  src/rust/lib/macro-utils/src/lib.rs
  src/rust/lib/shapely/impl/tests/derive_clone_ref.rs
  src/rust/lib/shapely/macros/src/derive_clone_ref.rs
  src/rust/lib/shapely/macros/src/lib.rs
Labels: Category: External, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#316 Fix #[derive(CloneRef)] for generic types with more than one type parameter.
  src/rust/lib/shapely/impl/tests/derive_clone_ref.rs
  src/rust/lib/shapely/macros/src/derive_clone_ref.rs
Labels: Category: External, Change: Non-Breaking, Difficulty: Beginner, Priority: High, Type: Enhancement

#277 Cache dependencies for CI.
  .github/workflows/build.yml
  .github/workflows/check.yml
  build/run.js
Labels: Category: Performance, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High

#314 IDE controllers refactoring
  src/rust/Cargo.lock
  src/rust/ensogl/src/lib.rs
  src/rust/ide/ast/impl/src/known.rs
  src/rust/ide/ast/impl/src/lib.rs
  src/rust/ide/file-manager/src/lib.rs
  src/rust/ide/parser/src/api.rs
  src/rust/ide/parser/src/jsclient.rs
  src/rust/ide/parser/src/lib.rs
  src/rust/ide/parser/src/main.rs
  src/rust/ide/parser/src/test_utils.rs
  src/rust/ide/parser/src/wsclient.rs
  src/rust/ide/parser/tests/ast.rs
  src/rust/ide/parser/tests/parsing.rs
  src/rust/ide/parser/tests/web.rs
  src/rust/ide/src/controller.rs
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/module.rs
  src/rust/ide/src/controller/project.rs
  src/rust/ide/src/controller/text.rs
  src/rust/ide/src/double_representation/definition.rs
  src/rust/ide/src/double_representation/graph.rs
  src/rust/ide/src/executor/test_utils.rs
  src/rust/ide/src/lib.rs
  src/rust/ide/src/model.rs
  src/rust/ide/src/model/module.rs
  src/rust/ide/src/model/module/registry.rs
  src/rust/ide/src/notification.rs
  src/rust/ide/src/transport/test_utils.rs
  src/rust/ide/src/view/layout.rs
  src/rust/ide/src/view/project.rs
  src/rust/ide/src/view/text_editor.rs
  src/rust/lib/logger/Cargo.toml
  src/rust/lib/logger/src/lib.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Enhancement
