Repository enso-org/ide, pull requests merged in 2020-06, with the labels that each got.

#504 Data as Text Visualization
  src/rust/ensogl/src/display/scene.rs
  src/rust/lib/graph-editor/src/component/visualization/container.rs
  src/rust/lib/graph-editor/src/component/visualization/registry.rs
  src/rust/lib/graph-editor/src/component/visualization/renderer/example/native.rs
Labels: Category: IDE, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#507 Extend graph editor api to allow data to be set on visualizations and stream the visibility status of visualisations.
  src/rust/lib/graph-editor/src/component/node.rs
  src/rust/lib/graph-editor/src/component/visualization/container.rs
  src/rust/lib/graph-editor/src/component/visualization/registry.rs
  src/rust/lib/graph-editor/src/component/visualization/renderer/example/native.rs
  src/rust/lib/graph-editor/src/lib.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#505 Fix: Mouse cursor has wrong position after scene resize.
  src/rust/ensogl/src/control/io/mouse.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#500 Integrating visualization data streaming with GUI
  build/run.js
  src/rust/ide/json-rpc/src/handler.rs
  src/rust/ide/json-rpc/src/lib.rs
  src/rust/ide/src/controller/graph/executed.rs
  src/rust/ide/src/lib.rs
  src/rust/ide/src/model/execution_context.rs
  src/rust/ide/src/model/module.rs
  src/rust/ide/src/model/synchronized/execution_context.rs
  src/rust/ide/src/view/layout.rs
  src/rust/ide/src/view/node_editor.rs
  src/rust/lib/frp/src/lib.rs
  src/rust/lib/frp/src/macros.rs
  src/rust/lib/frp/src/nodes.rs
  src/rust/lib/graph-editor/src/component/visualization/data.rs
  src/rust/lib/graph-editor/src/lib.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#532 Correctly invalidate line offsets after setting the text field's content
  src/rust/ensogl/src/display/shape/text/text_field/content.rs
  src/rust/lib/data/src/text.rs
Labels: Category: BaseGL API, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#536 DomSymbol y orientation fix
  src/rust/ensogl/src/display/symbol/dom.rs
  src/rust/lib/debug-scenes/src/dom_symbols.rs
Labels: Category: BaseGL Renderer, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#539 Bump parser to fix metadata loss on entering a newline
  src/rust/ide/parser/build.rs
  src/rust/ide/parser/tests/id_map.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#549 Visualisation FIXMEs
  src/rust/ide/src/controller/visualization.rs
  src/rust/lib/graph-editor/src/builtin/visualization/java_script.rs
  src/rust/lib/graph-editor/src/component/visualization/data.rs
  src/rust/lib/graph-editor/src/component/visualization/definition.rs
  src/rust/lib/graph-editor/src/component/visualization/foreign/java_script/definition.rs
  src/rust/lib/graph-editor/src/component/visualization/foreign/java_script/instance.rs
  src/rust/lib/graph-editor/src/component/visualization/instance.rs
  src/rust/lib/graph-editor/src/component/visualization/registry.rs
Labels: Category: IDE, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#519 Improved node searcher
  src/rust/Cargo.lock
  src/rust/ensogl/src/display/scene.rs
  src/rust/ide/Cargo.toml
  src/rust/ide/src/view/layout.rs
  src/rust/ide/src/view/node_searcher.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#552 Fixed textfield key masking on Mac
  .github/workflows/build.yml
  .github/workflows/check.yml
  run
  src/rust/ensogl/src/display/shape/text/text_field/frp/keyboard.rs
  src/rust/ide/src/view/text_editor.rs
  src/rust/lib/frp/src/io/keyboard.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#555 Css3d and navigation fixes
  src/rust/ensogl/src/display/navigation/navigator.rs
  src/rust/ensogl/src/display/navigation/navigator/events.rs
  src/rust/ensogl/src/display/scene/dom.rs
  src/rust/ensogl/src/display/symbol/dom.rs
Labels: Category: BaseGL API, Category: BaseGL Renderer, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug, Type: Enhancement

#557 Ensure the `node` is checked first.
  run
Labels: Category: External, Change: Non-Breaking, Difficulty: Intermediate, Priority: Lowest, Type: Enhancement

#553 Visualisation Fixes Part II
  src/rust/Cargo.toml
  src/rust/lib/graph-editor/src/builtin/visualization/java_script.rs
  src/rust/lib/graph-editor/src/builtin/visualization/native.rs
  src/rust/lib/graph-editor/src/builtin/visualization/native/bubble_chart.rs
  src/rust/lib/graph-editor/src/builtin/visualization/native/raw_text.rs
  src/rust/lib/graph-editor/src/component/visualization/container.rs
  src/rust/lib/graph-editor/src/component/visualization/data.rs
  src/rust/lib/graph-editor/src/component/visualization/definition.rs
  src/rust/lib/graph-editor/src/component/visualization/foreign/java_script.rs
  src/rust/lib/graph-editor/src/component/visualization/foreign/java_script/binding.rs
  src/rust/lib/graph-editor/src/component/visualization/foreign/java_script/definition.rs
  src/rust/lib/graph-editor/src/component/visualization/foreign/java_script/instance.rs
  src/rust/lib/graph-editor/src/component/visualization/foreign/java_script/visualization.js
  src/rust/lib/graph-editor/src/component/visualization/instance.rs
  src/rust/lib/graph-editor/src/component/visualization/registry.rs
  src/rust/lib/graph-editor/src/lib.rs
Labels: Category: IDE, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#556 Text API changes
  src/rust/Cargo.lock
  src/rust/ide/Cargo.toml
  src/rust/ide/ast/impl/src/lib.rs
  src/rust/ide/src/controller/module.rs
  src/rust/ide/src/double_representation/text.rs
  src/rust/ide/src/model/module.rs
  src/rust/ide/src/model/synchronized/module.rs
  src/rust/lib/data/src/text.rs
Labels: Category: IDE, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#563 Connect nodes starting from input ports.
  build/run.js
  src/rust/lib/graph-editor/src/component/cursor.rs
  src/rust/lib/graph-editor/src/component/edge.rs
  src/rust/lib/graph-editor/src/component/node.rs
  src/rust/lib/graph-editor/src/lib.rs
Labels: Category: IDE, Difficulty: Hard, Priority: High, Type: Enhancement

#569 Edge multi select
  src/rust/lib/graph-editor/src/lib.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Enhancement

#573 Fixing IDE layout by taking into consideration the new scene origin
  src/rust/ensogl/src/control/io/mouse.rs
  src/rust/ensogl/src/display/navigation/navigator.rs
  src/rust/ensogl/src/display/navigation/navigator/events.rs
  src/rust/ide/src/view/layout.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#525 Implement segmented output ports.
  build/run.js
  src/rust/ensogl/src/display/shape/primitive/def/class.rs
  src/rust/ensogl/src/display/shape/primitive/def/modifier.rs
  src/rust/ensogl/src/display/shape/primitive/def/var.rs
  src/rust/ensogl/src/display/shape/primitive/glsl/shape.glsl
  src/rust/ensogl/src/display/shape/primitive/shader/canvas.rs
  src/rust/lib/graph-editor/src/component/node.rs
  src/rust/lib/graph-editor/src/component/node/port.rs
  src/rust/lib/graph-editor/src/component/node/port/output.rs
  src/rust/lib/graph-editor/src/lib.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#580 Change visualization toggle shortcut to Ctrl+Space
  src/rust/lib/graph-editor/src/lib.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Beginner, Type: Enhancement

#582 Enable computation of SDF bounds for `grow` modifier.
  src/rust/ensogl/src/display/shape/primitive/glsl/shape.glsl
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Bug

#575 Use correct position to calculate edge dragging.
  src/rust/ensogl/src/display/scene.rs
  src/rust/lib/graph-editor/src/lib.rs
Labels: Category: IDE, Difficulty: Intermediate, Priority: High, Type: Bug

#583 Fix to work with latest engine
  src/js/package-lock.json
  src/rust/ide/enso-protocol/src/project_manager.rs
  src/rust/ide/src/lib.rs
  src/rust/ide/tests/project_manager.rs
Labels: Category: IDE, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#564 Routing type information to the graph editor integration layer
  build/run.js
  src/rust/ide/enso-protocol/src/language_server.rs
  src/rust/ide/enso-protocol/src/language_server/tests.rs
  src/rust/ide/enso-protocol/src/language_server/types.rs
  src/rust/ide/enso-protocol/src/project_manager.rs
  src/rust/ide/json-rpc/src/macros.rs
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/graph/executed.rs
  src/rust/ide/src/controller/project.rs
  src/rust/ide/src/executor/test_utils.rs
  src/rust/ide/src/lib.rs
  src/rust/ide/src/model/execution_context.rs
  src/rust/ide/src/model/synchronized/execution_context.rs
  src/rust/ide/src/view/node_editor.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#599 Expression id in span tree
  build/run.js
  src/rust/ide/ast/impl/src/lib.rs
  src/rust/ide/ast/impl/src/opr.rs
  src/rust/ide/ast/impl/src/prefix.rs
  src/rust/ide/parser/src/lib.rs
  src/rust/ide/span-tree/src/action.rs
  src/rust/ide/span-tree/src/builder.rs
  src/rust/ide/span-tree/src/generate.rs
  src/rust/ide/span-tree/src/lib.rs
  src/rust/ide/span-tree/src/node.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#602 Passing Type Information To Graph Editor View
  src/rust/ide/src/controller/graph/executed.rs
  src/rust/ide/src/controller/project.rs
  src/rust/ide/src/model/execution_context.rs
  src/rust/ide/src/view/node_editor.rs
  src/rust/lib/graph-editor/src/lib.rs
  src/rust/lib/prelude/src/string.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#578 Open project with CLI arg
  build/run.js
  src/js/lib/client/src/index.js
  src/js/package-lock.json
  src/rust/ide/enso-protocol/src/project_manager.rs
  src/rust/ide/src/config.rs
  src/rust/ide/src/constants.rs
  src/rust/ide/src/controller/project.rs
  src/rust/ide/src/controller/visualization.rs
  src/rust/ide/src/ide.rs
  src/rust/ide/src/lib.rs
  src/rust/ide/src/model/module.rs
  src/rust/ide/src/model/synchronized/execution_context.rs
  src/rust/ide/src/tests.rs
  src/rust/ide/src/view/layout.rs
  src/rust/ide/src/view/node_editor.rs
  src/rust/ide/src/view/project.rs
  src/rust/ide/tests/language_server.rs
  src/rust/ide/tests/project_manager.rs
  src/rust/lib/debug-scenes/src/ide.rs
  src/rust/lib/system/web/Cargo.toml
  src/rust/lib/system/web/src/lib.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#607 The last selected node may be entered by pressing Ctrl+Enter.
  docs/shortcuts.md
  src/rust/ide/src/view/node_editor.rs
  src/rust/lib/graph-editor/src/lib.rs
Labels: Category: IDE, Change: Non-Breaking, Difficulty: Core Contributor, Type: Enhancement

#608 Refactor update -> refresh in the graph editor integration
  src/rust/ide/src/view/node_editor.rs
Labels: Category: IDE, Change: Breaking, Difficulty: Beginner, Type: Enhancement

#615 Bump websocket-extension version
  src/js/package-lock.json
Labels: Category: External, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Bug

#586 fix: Avoid clipping the edges of the multi port shape.
  src/rust/lib/graph-editor/src/component/node/port/output.rs
Labels: Category: IDE, Difficulty: Intermediate, Priority: High, Type: Bug
