Repository enso-org/ide, pull requests merged in 2020-01, with the labels that each got.

#93 Cursors in text
  lib/core/src/display/render/webgl.rs
  lib/core/src/display/shape/text.rs
  lib/core/src/display/shape/text/buffer.rs
  lib/core/src/display/shape/text/buffer/fragment.rs
  lib/core/src/display/shape/text/buffer/glyph_square.rs
  lib/core/src/display/shape/text/buffer/line.rs
  lib/core/src/display/shape/text/content.rs
  lib/core/src/display/shape/text/content/line.rs
  lib/core/src/display/shape/text/cursor.rs
  lib/core/src/display/shape/text/program.rs
  lib/core/src/display/shape/text/program/cursor_frag.glsl
  lib/core/src/display/shape/text/program/cursor_vert.glsl
  lib/core/src/display/shape/text/program/msdf_frag.glsl
  lib/core/src/display/shape/text/program/msdf_vert.glsl
  lib/core/src/display/world.rs
  lib/core/src/lib.rs
  lib/core/tests/text.rs
Labels: Category: API, Category: Renderer, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Enhancement

#60 Camera Animation System
  Cargo.toml
  lib/core/Cargo.toml
  lib/core/src/animation.rs
  lib/core/src/animation/animator.rs
  lib/core/src/animation/animator/continuous.rs
  lib/core/src/animation/animator/fixed_step.rs
  lib/core/src/animation/continuous_time_animator.rs
  lib/core/src/animation/physics.rs
  lib/core/src/animation/physics/inertia.rs
  lib/core/src/control.rs
  lib/core/src/control/mouse_manager.rs
  lib/core/src/data.rs
  lib/core/src/display.rs
  lib/core/src/display/navigation.rs
  lib/core/src/display/navigation/navigator.rs
  lib/core/src/display/navigation/navigator/events.rs
  lib/core/src/display/object.rs
  lib/core/src/display/render/css3d/camera.rs
  lib/core/src/display/render/css3d/dom_container.rs
  lib/core/src/display/render/css3d/graphics_renderer.rs
  lib/core/src/display/render/css3d/html/html_renderer.rs
  lib/core/src/display/render/css3d/html/snippets.js
  lib/core/src/display/render/css3d/scene.rs
  lib/core/src/display/render/css3d/transform.rs
  lib/core/src/display/symbol/registry.rs
  lib/core/src/display/world/event_loop.rs
  lib/core/src/examples.rs
  lib/core/src/examples/camera_navigation.rs
  lib/core/src/lib.rs
  lib/core/src/math.rs
  lib/core/src/math/utils.rs
  lib/core/src/system/gpu/data/attribute.rs
  lib/core/tests/html_renderer.rs
  lib/core/tests/navigation.rs
  lib/core/tests/physics_simulator.rs
  lib/core/tests/text.rs
  lib/data/Cargo.toml
  lib/data/src/lib.rs
  lib/data/src/opt_vec.rs
  lib/system/web/Cargo.toml
  lib/system/web/js/intersection_observer.js
  lib/system/web/src/animation_frame_loop.rs
  lib/system/web/src/intersection_observer.rs
  lib/system/web/src/lib.rs
  lib/web-test/src/bencher.rs
Labels: Category: API, Category: Documentation, Category: Renderer, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#106 Cursor navigation
  lib/core/src/display/render/webgl.rs
  lib/core/src/display/shape/text.rs
  lib/core/src/display/shape/text/content.rs
  lib/core/src/display/shape/text/cursor.rs
  lib/core/src/examples/text.rs
  lib/core/tests/text.rs
Labels: Category: API, Change: Non-Breaking, Difficulty: Beginner, Priority: High, Type: Enhancement

#112 Texture rendering
  lib/core/src/display/symbol.rs
  lib/core/src/display/symbol/material.rs
  lib/core/src/display/world.rs
  lib/core/src/system/gpu/data.rs
  lib/core/src/system/gpu/data/buffer/item.rs
  lib/core/src/system/gpu/data/texture.rs
  lib/core/src/system/gpu/data/uniform.rs
  lib/core/src/system/gpu/shader/glsl.rs
Labels: Category: API, Category: Renderer, Change: Breaking, Difficulty: Hard, Priority: Highest, Type: Enhancement

#113 Using Firefox for headless web tests
  .github/workflows/build.yml
  script/test.sh
Labels: Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Bug

#108 Animation Manager (aka EasingAnimator)
  lib/core/src/animation.rs
  lib/core/src/animation/animator.rs
  lib/core/src/animation/animator/continuous.rs
  lib/core/src/animation/animator/easing.rs
  lib/core/src/animation/animator/fixed_step.rs
  lib/core/src/animation/easing.rs
  lib/core/src/animation/physics.rs
  lib/core/src/animation/physics/inertia.rs
  lib/core/src/animation/position.rs
  lib/core/src/control.rs
  lib/core/src/control/callback.rs
  lib/core/src/control/event_loop.rs
  lib/core/src/control/io/mouse.rs
  lib/core/src/display/navigation/navigator.rs
  lib/core/src/display/world.rs
  lib/core/src/examples.rs
  lib/core/src/examples/camera_navigation.rs
  lib/core/src/examples/easing_animator.rs
  lib/core/src/system/web/dom/dom_container.rs
  lib/core/src/system/web/dom/graphics_renderer.rs
  lib/core/src/system/web/dom/html/html_object.rs
  lib/core/src/system/web/dom/html/html_renderer.rs
  lib/core/src/system/web/dom/object.rs
  lib/core/tests/html_renderer.rs
  lib/core/tests/navigation.rs
  lib/core/tests/physics_simulator.rs
  lib/logger/src/lib.rs
  lib/system/web/src/animation_frame_loop.rs
  lib/system/web/src/lib.rs
  lib/system/web/src/resize_observer.rs
  lib/web-test/Cargo.toml
  lib/web-test/src/bench_container.rs
  lib/web-test/src/bencher.rs
  lib/web-test/src/container.rs
  lib/web-test/src/group.rs
Labels: Category: API, Category: Documentation, Category: Performance, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Enhancement

#119 Integration of WebGL and CSS scenes and renderers
  lib/core/src/animation/animator.rs
  lib/core/src/animation/animator/continuous.rs
  lib/core/src/animation/animator/easing.rs
  lib/core/src/animation/animator/fixed_step.rs
  lib/core/src/animation/physics/inertia.rs
  lib/core/src/control/io/mouse.rs
  lib/core/src/debug/stats.rs
  lib/core/src/display/camera/camera2d.rs
  lib/core/src/display/navigation/navigator.rs
  lib/core/src/display/navigation/navigator/events.rs
  lib/core/src/display/object.rs
  lib/core/src/display/scene.rs
  lib/core/src/display/world.rs
  lib/core/src/examples.rs
  lib/core/src/examples/camera_navigation.rs
  lib/core/src/examples/easing_animator.rs
  lib/core/src/examples/shapes.rs
  lib/core/src/examples/sprite_system.rs
  lib/core/src/examples/text.rs
  lib/core/src/system/web/dom.rs
  lib/core/src/system/web/dom/camera.rs
  lib/core/src/system/web/dom/dom_container.rs
  lib/core/src/system/web/dom/graphics_renderer.rs
  lib/core/src/system/web/dom/html.rs
  lib/core/src/system/web/dom/html/html_object.rs
  lib/core/src/system/web/dom/html/html_renderer.rs
  lib/core/src/system/web/dom/html/html_scene.rs
  lib/core/src/system/web/dom/html/snippets.js
  lib/core/src/system/web/dom/htmlscene.rs
  lib/core/src/system/web/dom/object.rs
  lib/core/src/system/web/dom/scene.rs
  lib/core/src/system/web/dom/transform.rs
  lib/core/tests/html_renderer.rs
  lib/core/tests/navigation.rs
  lib/core/tests/physics_simulator.rs
  lib/core/tests/text.rs
  lib/logger/src/lib.rs
  lib/system/web/Cargo.toml
  lib/system/web/src/dom.rs
  lib/system/web/src/dom/dom_container.rs
  lib/system/web/src/intersection_observer.rs
  lib/system/web/src/lib.rs
Labels: Category: Renderer, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#127 Run wasm-pack test on Windows and macOS
  .github/workflows/build.yml
Labels: Category: External, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement
