Repository enso-org/ide, pull requests merged in 2021-02, with the labels that each got.

#1172 Implement basic dragging for visualisation containers.
  src/rust/ensogl/lib/core/src/gui/cursor.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container/action_bar.rs
Labels: Category: GUI, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1166 Integrate setPreprocessor function with Engine
  build/package.json
  docs/product/visualizations.md
  src/rust/ide/src/controller/graph/executed.rs
  src/rust/ide/src/controller/visualization.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/src/model/execution_context.rs
  src/rust/ide/src/model/execution_context/plain.rs
  src/rust/ide/src/model/execution_context/synchronized.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/histogram.js
  src/rust/ide/view/graph-editor/src/component/visualization/container.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
  src/rust/ide/view/graph-editor/src/component/visualization/definition.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/definition.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs
  src/rust/ide/view/graph-editor/src/component/visualization/instance.rs
  src/rust/ide/view/graph-editor/src/component/visualization/path.rs
  src/rust/ide/view/graph-editor/src/component/visualization/registry.rs
  src/rust/ide/view/graph-editor/src/data.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/src/debug_scenes/visualization.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Hard, Priority: High, Type: Enhancement

#1181 Enable table visualisation for Tables.
  CHANGELOG.md
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/table.js
Labels: Category: Visualizations, Difficulty: Hard, Priority: High, Type: Enhancement

#1190 A shortcut for reloading visualization files.
  CHANGELOG.md
  docs/product/shortcuts.md
  src/rust/ensogl/lib/core/src/display/object/class.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/view/graph-editor/src/component/visualization/registry.rs
  src/rust/ide/view/graph-editor/src/lib.rs
Labels: Category: GUI, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#1194 Change visualization reload shortcut
  docs/product/shortcuts.md
  src/rust/ide/view/graph-editor/src/lib.rs
Labels: Category: GUI, Good First Issue, Priority: Highest, Type: Bug

#1191 Fix aliasing artficats on repeated shapes: Correct repeat shape function to not cut of shapes.
  src/rust/ensogl/lib/core/src/display/shape/primitive/glsl/shape.glsl
  src/rust/ensogl/lib/core/src/display/shape/primitive/shader/canvas.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
Labels: Category: BaseGL, Priority: High, Type: Bug

#1160 Add API to mark node VCS status.
  CHANGELOG.md
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/node/vcs.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/src/debug_scenes/interface.rs
Labels: Category: GUI, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1182 Integrate errors view with engine
  CHANGELOG.md
  docs/CONTRIBUTING.md
  src/js/lib/project-manager/src/build.ts
  src/rust/Cargo.lock
  src/rust/ide/Cargo.toml
  src/rust/ide/lib/enso-protocol/src/language_server/tests.rs
  src/rust/ide/lib/enso-protocol/src/language_server/types.rs
  src/rust/ide/lib/enso-protocol/src/lib.rs
  src/rust/ide/lib/enso-protocol/src/project_manager.rs
  src/rust/ide/src/ide.rs
  src/rust/ide/src/ide/initializer.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/src/lib.rs
  src/rust/ide/src/model/execution_context.rs
  src/rust/ide/src/model/execution_context/synchronized.rs
  src/rust/ide/src/model/project.rs
  src/rust/ide/src/model/project/synchronized.rs
  src/rust/ide/view/src/lib.rs
  src/rust/ide/view/src/project.rs
  src/rust/ide/view/src/status_bar.rs
Labels: Category: Controllers, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1186 Update AST - new import syntax etc.
  src/rust/ide/lib/ast/impl/src/crumbs.rs
  src/rust/ide/lib/ast/impl/src/lib.rs
  src/rust/ide/lib/ast/impl/src/macros.rs
  src/rust/ide/lib/ast/impl/src/repr.rs
  src/rust/ide/lib/parser/build.rs
  src/rust/ide/lib/parser/tests/bugs.rs
  src/rust/ide/lib/parser/tests/macros.rs
  src/rust/ide/lib/parser/tests/parsing.rs
  src/rust/ide/src/double_representation/module.rs
Labels: Category: GUI, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1198 Nodes added by searcher will always use assignment form.
  CHANGELOG.md
  src/rust/Cargo.toml
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/searcher.rs
Labels: Category: GUI, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1187 Update geomaps to allow dataframes as input.
  CHANGELOG.md
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/geoMap.js
Labels: Category: Visualizations, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1203 Umarking node if it is erroneous no more
  src/rust/ide/src/ide/integration.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Intermediate, Priority: Highest, Type: Bug

#1206 Update controller to take into account visualisation metadata from the IDE when attaching a visualisation.
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/view/graph-editor/src/component/visualization.rs
  src/rust/ide/view/graph-editor/src/component/visualization/metadata.rs
  src/rust/ide/view/graph-editor/src/lib.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Intermediate, Priority: High, Type: Bug, Type: Enhancement

#1215 Error Visualizations
  CHANGELOG.md
  src/js/lib/project-manager/src/build.ts
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/src/constants.rs
  src/rust/ide/src/ide/initializer.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/src/model/execution_context.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/native.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/native/error.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/node/error.rs
  src/rust/ide/view/graph-editor/src/component/node/output/area.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container.rs
  src/rust/ide/view/graph-editor/src/component/visualization/instance.rs
  src/rust/ide/view/graph-editor/src/component/visualization/metadata.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/src/debug_scenes/interface.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1252 Fix eye icon
  src/rust/ensogl/lib/components/src/toggle_button.rs
  src/rust/ide/src/ide/initializer.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/node/action_bar.rs
Labels: Category: GUI, Difficulty: Intermediate, Priority: Highest, Type: Bug

#1261 Fix computing the minimal diff sent to the Engine
  src/rust/ide/lib/enso-protocol/src/language_server/types.rs
Labels: Category: Controllers, Difficulty: Intermediate, Priority: Highest, Type: Bug

#1262 Keep progress indicator visible and capped at 30%
  CHANGELOG.md
  src/js/lib/common/src/loader.js
  src/js/lib/content/src/index.js
  src/js/lib/content/src/style.css
Labels: Category: GUI, Priority: Highest, Type: Enhancement

#1264 A set of small fixes
  src/js/lib/client/src/index.js
  src/rust/ide/lib/ast/impl/src/crumbs.rs
  src/rust/ide/lib/ast/impl/src/lib.rs
  src/rust/ide/lib/ast/impl/src/repr.rs
  src/rust/ide/lib/parser/build.rs
  src/rust/ide/lib/parser/tests/bugs.rs
  src/rust/ide/lib/parser/tests/parsing.rs
  src/rust/ide/src/ide.rs
  src/rust/ide/view/graph-editor/src/component/node/input/area.rs
  src/rust/ide/view/src/status_bar.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Hard, Priority: Highest, Type: Bug

#1266 Revert the sign in movement_to_zoom
  src/rust/ensogl/lib/core/src/display/navigation/navigator/events.rs
Labels: Category: BaseGL, Good First Issue, Priority: Highest, Type: Bug

#1267 Allow geomap preprocessor to work without Table import.
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/geoMap.js
Labels: Category: Visualizations, Priority: Highest, Type: Bug

#1272 Bump Engine's version to 0.2.5
  src/js/lib/project-manager/src/build.ts
  src/rust/ide/src/ide/initializer.rs
Labels: Category: Controllers, Difficulty: Intermediate, Priority: Highest, Type: Bug

#1271 Node positioning improvements
  src/rust/Cargo.lock
  src/rust/ide/lib/utils/Cargo.toml
  src/rust/ide/lib/utils/src/iter.rs
  src/rust/ide/lib/utils/src/lib.rs
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/src/model/module.rs
Labels: Category: GUI, Priority: Highest, Type: Enhancement
