Repository enso-org/ide, pull requests merged in 2021-07, with the labels that each got.

#1614 Scrollbar and ScrollArea
  src/rust/ensogl/example/src/lib.rs
  src/rust/ensogl/example/src/scroll_area.rs
  src/rust/ensogl/lib/components/src/lib.rs
  src/rust/ensogl/lib/components/src/scroll_area.rs
  src/rust/ensogl/lib/components/src/scrollbar.rs
  src/rust/ensogl/lib/components/src/selector.rs
  src/rust/ensogl/lib/components/src/selector/bounds.rs
  src/rust/ensogl/lib/components/src/selector/frp.rs
  src/rust/ensogl/lib/components/src/selector/model.rs
  src/rust/ensogl/lib/components/src/selector/number.rs
  src/rust/ensogl/lib/components/src/selector/range.rs
  src/rust/ensogl/lib/components/src/selector/shape.rs
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/lib/types/src/algebra.rs
Labels: Category: GUI, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1664 Emit correct events when deselecting all nodes.
  CHANGELOG.md
  src/rust/ide/src/ide.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/graph-editor/src/selection.rs
Labels: Category: GUI, Priority: Highest, Type: Regression

#1653 User Authentication in IDE
  .github/workflows/gui-ci.yml
  CHANGELOG.md
  build/workflow.js
  config.json
  src/js/lib/client/src/index.js
  src/js/lib/content/firebase.yaml
  src/js/lib/content/package.js
  src/js/lib/content/src/index.html
  src/js/lib/content/src/index.ts
  src/js/lib/content/src/style.css
  src/js/lib/content/webpack.config.js
Labels: Category: GUI, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1699 Create new unstable releases as draft.
  .github/workflows/gui-ci.yml
  build/workflow.js
Labels: Category: Build System, Type: Enhancement

#1710 Engine 0.2.15
  CHANGELOG.md
  src/js/lib/client/tasks/signArchives.js
  src/js/lib/project-manager/src/build.ts
  src/rust/ide/lib/args/src/lib.rs
  src/rust/ide/lib/enso-protocol/src/language_server/connection.rs
  src/rust/ide/lib/enso-protocol/src/language_server/tests.rs
  src/rust/ide/lib/enso-protocol/src/language_server/types.rs
  src/rust/ide/lib/enso-protocol/src/project_manager.rs
  src/rust/ide/lib/parser/build.rs
  src/rust/ide/lib/parser/tests/macros.rs
  src/rust/ide/lib/parser/tests/parsing.rs
  src/rust/ide/src/config.rs
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/graph/executed.rs
  src/rust/ide/src/controller/ide.rs
  src/rust/ide/src/controller/ide/desktop.rs
  src/rust/ide/src/controller/ide/plain.rs
  src/rust/ide/src/controller/module.rs
  src/rust/ide/src/controller/project.rs
  src/rust/ide/src/controller/searcher.rs
  src/rust/ide/src/controller/searcher/action.rs
  src/rust/ide/src/controller/upload.rs
  src/rust/ide/src/controller/visualization.rs
  src/rust/ide/src/double_representation.rs
  src/rust/ide/src/double_representation/module.rs
  src/rust/ide/src/double_representation/project.rs
  src/rust/ide/src/double_representation/tp.rs
  src/rust/ide/src/ide.rs
  src/rust/ide/src/ide/initializer.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/src/model/execution_context/plain.rs
  src/rust/ide/src/model/module.rs
  src/rust/ide/src/model/project.rs
  src/rust/ide/src/model/project/synchronized.rs
  src/rust/ide/src/model/suggestion_database/entry.rs
  src/rust/ide/src/test.rs
  src/rust/ide/tests/language_server.rs
Labels: Category: Build System, Category: Controllers, Difficulty: Hard, Priority: Highest, Type: Enhancement

#1722 Modify list view api to support custom entry
  src/rust/ensogl/example/src/list_view.rs
  src/rust/ensogl/lib/components/src/drop_down_menu.rs
  src/rust/ensogl/lib/components/src/list_view.rs
  src/rust/ensogl/lib/components/src/list_view/entry.rs
  src/rust/ensogl/lib/components/src/list_view/entry/list.rs
  src/rust/ensogl/lib/core/src/application/frp.rs
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
  src/rust/ide/view/graph-editor/src/component/visualization/path.rs
  src/rust/ide/view/src/searcher.rs
Labels: Category: GUI, Difficulty: Hard, Priority: Highest, Type: Enhancement

#1700 File Open Dialog
  CHANGELOG.md
  src/js/lib/content/package-lock.json
  src/rust/ensogl/lib/components/src/file_browser.rs
  src/rust/ensogl/lib/components/src/file_browser/model.rs
  src/rust/ensogl/lib/components/src/lib.rs
  src/rust/ensogl/lib/components/src/list_view.rs
  src/rust/ensogl/lib/core/src/display/object/class.rs
  src/rust/ensogl/lib/core/src/display/scene.rs
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/lib/enso-protocol/src/language_server/types.rs
  src/rust/ide/src/controller/project.rs
  src/rust/ide/src/controller/upload.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/src/ide/integration/file_system.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/src/model/project.rs
  src/rust/ide/src/model/project/synchronized.rs
  src/rust/ide/tests/language_server.rs
  src/rust/ide/view/src/lib.rs
  src/rust/ide/view/src/open_dialog.rs
  src/rust/ide/view/src/open_dialog/project_list.rs
  src/rust/ide/view/src/project.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1715 Searcher icons 1
  src/rust/ensogl/lib/core/src/display/shape/primitive/def/primitive.rs
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/view/src/searcher.rs
  src/rust/ide/view/src/searcher/icons.rs
Labels: Category: GUI, Priority: High, Type: Enhancement

#1723 Searcher Icons 2
  src/rust/ensogl/lib/core/src/display/shape/primitive/def/primitive.rs
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/view/src/searcher/icons.rs
Labels: Category: GUI, Type: Enhancement

#1726 Bump engine to 0.2.16
  CHANGELOG.md
  src/js/lib/client/tasks/signArchives.js
  src/js/lib/project-manager/src/build.ts
  src/rust/ide/lib/enso-protocol/src/language_server/types.rs
  src/rust/ide/src/controller/project.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/src/model/suggestion_database/entry.rs
Labels: Category: Build System, Category: Controllers, Type: Enhancement

#1733 Searcher Icons 3
  src/rust/ensogl/lib/core/src/display/shape/compound.rs
  src/rust/ensogl/lib/core/src/display/shape/compound/path.rs
  src/rust/ensogl/lib/core/src/display/shape/primitive/def/primitive.rs
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/view/src/searcher/icons.rs
Labels: Category: GUI

#1741 Hardcoded suggestions and categories in searcher controller.
  src/rust/ensogl/lib/components/src/file_browser/model.rs
  src/rust/ide/src/controller/searcher.rs
  src/rust/ide/src/controller/searcher/action.rs
  src/rust/ide/src/controller/searcher/action/hardcoded.rs
  src/rust/ide/src/double_representation/tp.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/src/model/suggestion_database/entry.rs
  src/rust/ide/src/tests.rs
Labels: Category: Controllers, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1743 Fix expression changing during editing
  CHANGELOG.md
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/view/graph-editor/src/component/node/expression.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Intermediate, Priority: High, Type: Bug
