Repository enso-org/ide, pull requests merged in 2021-05, with the labels that each got.

#1536 Correctly interpret string arguments as booleans in electron arguments.
  CHANGELOG.md
  src/js/lib/content/src/index.js
Labels: Category: GUI, Difficulty: Hard, Priority: Highest, Type: Bug

#1537 Reconnecting WS
  src/rust/ide/Cargo.toml
  src/rust/ide/lib/json-rpc/src/transport.rs
  src/rust/ide/src/executor/test_utils.rs
  src/rust/ide/src/executor/web.rs
  src/rust/ide/src/executor/web/test.rs
  src/rust/ide/src/ide/initializer.rs
  src/rust/ide/src/transport/web.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs
  src/rust/lib/system/web/src/closure/storage.rs
  src/rust/lib/system/web/src/event.rs
  src/rust/lib/system/web/src/event/listener.rs
  src/rust/lib/system/web/src/lib.rs
Labels: Category: Controllers, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1556 Deselect visualization when its node gets removed
  CHANGELOG.md
  src/rust/ide/view/graph-editor/src/lib.rs
Labels: Category: GUI, Priority: High, Type: Bug

#1427 Show node output type right under the node, not in pop-up.
  CHANGELOG.md
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/node/action_bar.rs
  src/rust/ide/view/graph-editor/src/component/node/output/area.rs
  src/rust/ide/view/graph-editor/src/component/node/output/port.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/src/project.rs
Labels: Category: GUI, Priority: Highest, Type: Enhancement

#1568 Add missing parameters in ts Config class
  .prettierignore
  src/js/lib/content/src/index.ts
  src/rust/ensogl/lib/core/src/application/args.rs
Labels: Difficulty: Intermediate, Priority: High, Type: Bug

#1524 Implement number and range pickers.
  CHANGELOG.md
  src/rust/Cargo.lock
  src/rust/ensogl/example/src/leak.rs
  src/rust/ensogl/example/src/lib.rs
  src/rust/ensogl/example/src/slider.rs
  src/rust/ensogl/lib/components/Cargo.toml
  src/rust/ensogl/lib/components/src/component.rs
  src/rust/ensogl/lib/components/src/lib.rs
  src/rust/ensogl/lib/components/src/selector.rs
  src/rust/ensogl/lib/components/src/selector/bounds.rs
  src/rust/ensogl/lib/components/src/selector/decimal_aligned.rs
  src/rust/ensogl/lib/components/src/selector/frp.rs
  src/rust/ensogl/lib/components/src/selector/model.rs
  src/rust/ensogl/lib/components/src/selector/number.rs
  src/rust/ensogl/lib/components/src/selector/range.rs
  src/rust/ensogl/lib/components/src/selector/shape.rs
  src/rust/ensogl/lib/components/src/shadow.rs
  src/rust/ensogl/lib/core/src/application/frp.rs
  src/rust/ensogl/lib/core/src/data/color/space/def.rs
  src/rust/ensogl/lib/core/src/display/shape/primitive/style_watch.rs
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/lib/frp/src/nodes.rs
Labels: Category: BaseGL, Category: GUI, Difficulty: Hard, Priority: High, Type: Enhancement

#1566 Create new project action in searcher.
  CHANGELOG.md
  src/rust/ide/lib/enso-protocol/src/language_server/types.rs
  src/rust/ide/lib/enso-protocol/src/project_manager.rs
  src/rust/ide/src/controller.rs
  src/rust/ide/src/controller/ide.rs
  src/rust/ide/src/controller/ide/desktop.rs
  src/rust/ide/src/controller/ide/plain.rs
  src/rust/ide/src/controller/project.rs
  src/rust/ide/src/controller/searcher.rs
  src/rust/ide/src/controller/searcher/action.rs
  src/rust/ide/src/ide.rs
  src/rust/ide/src/ide/initializer.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/src/model/project.rs
  src/rust/ide/src/model/project/synchronized.rs
  src/rust/ide/src/test.rs
  src/rust/ide/src/tests.rs
  src/rust/ide/tests/language_server.rs
  src/rust/ide/view/src/status_bar.rs
Labels: Category: Controllers, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1578 Fix Cursor Position in Cloud and Bug in Creating New Projects
  src/js/lib/content/src/index.html
  src/js/lib/content/src/style.css
  src/rust/ensogl/lib/core/src/display/scene.rs
  src/rust/ide/src/controller/ide/desktop.rs
Labels: Category: BaseGL, Difficulty: Intermediate, Priority: High, Type: Bug

#1581 Add missing type annotations and allow imports in project-manager build file.
  src/js/lib/project-manager/src/build.ts
Labels: Category: Build System, Difficulty: Intermediate, Priority: Highest, Type: Bug

#1577 Searcher Fixes
  CHANGELOG.md
  src/rust/ensogl/lib/components/src/label.rs
  src/rust/ensogl/lib/components/src/list_view.rs
  src/rust/ensogl/lib/components/src/list_view/entry.rs
  src/rust/ensogl/lib/components/src/selector/decimal_aligned.rs
  src/rust/ensogl/lib/components/src/selector/model.rs
  src/rust/ensogl/lib/core/src/display/scene.rs
  src/rust/ensogl/lib/core/src/gui/cursor.rs
  src/rust/ensogl/lib/text/src/component/area.rs
  src/rust/ide/view/graph-editor/src/component/breadcrumbs.rs
  src/rust/ide/view/graph-editor/src/component/breadcrumbs/breadcrumb.rs
  src/rust/ide/view/graph-editor/src/component/breadcrumbs/project_name.rs
  src/rust/ide/view/graph-editor/src/component/node/input/area.rs
  src/rust/ide/view/graph-editor/src/component/node/output/area.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container.rs
  src/rust/ide/view/src/code_editor.rs
  src/rust/ide/view/src/project.rs
  src/rust/ide/view/src/searcher.rs
  src/rust/ide/view/src/status_bar.rs
Labels: Category: BaseGL, Category: GUI, Difficulty: Hard, Priority: High, Type: Enhancement
