Repository enso-org/ide, pull requests merged in 2021-01, with the labels that each got.

#1093 Bump ProjectManager version
  src/js/lib/project-manager/src/build.ts
Labels: Good First Issue, Priority: High, Type: Enhancement

#1108 Fix output edge coloring
  src/rust/ide/lib/ast/impl/src/test_utils.rs
  src/rust/ide/view/graph-editor/src/component/node/output/area.rs
  src/rust/ide/view/graph-editor/src/lib.rs
Labels: Category: GUI, Difficulty: Intermediate, Priority: High, Type: Bug

#1112 Use newest enso-prelude and enso-logger
  src/rust/Cargo.lock
  src/rust/ensogl/example/Cargo.toml
  src/rust/ensogl/lib/components/Cargo.toml
  src/rust/ensogl/lib/core/Cargo.toml
  src/rust/ensogl/lib/text/Cargo.toml
  src/rust/ensogl/lib/text/embedded-fonts/Cargo.toml
  src/rust/ensogl/lib/text/msdf-sys/Cargo.toml
  src/rust/ide/Cargo.toml
  src/rust/ide/lib/args/Cargo.toml
  src/rust/ide/lib/ast/impl/Cargo.toml
  src/rust/ide/lib/ast/macros/Cargo.toml
  src/rust/ide/lib/enso-protocol/Cargo.toml
  src/rust/ide/lib/json-rpc/Cargo.toml
  src/rust/ide/lib/parser/Cargo.toml
  src/rust/ide/lib/span-tree/Cargo.toml
  src/rust/ide/lib/span-tree/example/Cargo.toml
  src/rust/ide/lib/utils/Cargo.toml
  src/rust/ide/view/Cargo.toml
  src/rust/ide/view/graph-editor/Cargo.toml
  src/rust/lib/callback/Cargo.toml
  src/rust/lib/code-builder/Cargo.toml
  src/rust/lib/frp/Cargo.toml
  src/rust/lib/fuzzly/Cargo.toml
  src/rust/lib/shortcuts/Cargo.toml
  src/rust/lib/shortcuts/example/Cargo.toml
  src/rust/lib/system/web/Cargo.toml
  src/rust/lib/web-test/Cargo.toml
Labels: Good First Issue, Priority: Highest, Type: Bug

#1091 CDN pipeline
  .github/workflows/release.yml
  src/js/lib/client/src/index.js
  src/js/lib/common/src/loader.js
  src/js/lib/content/src/index.html
  src/js/lib/content/src/index.js
  src/js/lib/content/src/style.css
  src/js/lib/content/webpack.config.js
  src/rust/ide/lib/args/src/lib.rs
Labels: Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1104 Enable the watch script to download and use the pre-built project manager.
  build/paths.js
  build/run.js
  src/js/lib/client/src/preload.js
Labels: Difficulty: Intermediate, Priority: High, Type: Bug, Type: Enhancement

#1124 Avoid panning jumps when mouse cursor changes html element.
  src/rust/ensogl/lib/core/src/control/io/mouse/event.rs
  src/rust/ensogl/lib/core/src/display/navigation/navigator/events.rs
  src/rust/lib/system/web/Cargo.toml
Labels: Category: BaseGL, Category: GUI, Priority: High, Type: Bug

#1113 Use bordered windows for the electron app on non-MacOS platforms.
  src/js/lib/client/src/index.js
Labels: Difficulty: Intermediate, Priority: Highest, Type: Bug

#1130 Upgrade to engine 0.2.1
  src/js/lib/project-manager/src/build.ts
  src/js/package-lock.json
  src/rust/ide/lib/enso-protocol/src/language_server/types.rs
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/graph/executed.rs
  src/rust/ide/src/controller/module.rs
  src/rust/ide/src/controller/searcher.rs
  src/rust/ide/src/controller/searcher/action.rs
  src/rust/ide/src/double_representation.rs
  src/rust/ide/src/double_representation/identifier.rs
  src/rust/ide/src/double_representation/module.rs
  src/rust/ide/src/double_representation/tp.rs
  src/rust/ide/src/ide.rs
  src/rust/ide/src/ide/initializer.rs
  src/rust/ide/src/model/execution_context/plain.rs
  src/rust/ide/src/model/module.rs
  src/rust/ide/src/model/suggestion_database.rs
  src/rust/ide/src/model/suggestion_database/entry.rs
  src/rust/ide/src/test.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1131 Update build to correctly bundle the engine.
  src/js/lib/client/package.js
  src/js/lib/client/src/index.js
Labels: Priority: Highest, Type: Bug, Type: Enhancement

#1133 Upgrade wasm pack from 0.8.1 to 0.9.1.
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/release.yml
  docs/CONTRIBUTING.md
Labels: Difficulty: Intermediate, Priority: Highest, Type: Bug

#1138 Implement remote logging.
  package-lock.json
  src/js/lib/content/package.js
  src/js/lib/content/src/index.js
  src/js/package-lock.json
  src/rust/Cargo.lock
  src/rust/ide/Cargo.toml
  src/rust/ide/lib/analytics/Cargo.toml
  src/rust/ide/lib/analytics/src/data.rs
  src/rust/ide/lib/analytics/src/lib.rs
  src/rust/ide/lib/analytics/src/remote_log.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/view/graph-editor/Cargo.toml
  src/rust/ide/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Intermediate, Priority: Highest

#1152 Update to logging.
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
Labels: Priority: Highest, Type: Enhancement
