Repository enso-org/ide, pull requests merged in 2021-09, with the labels that each got.

#1831 Fix parsing of the {no-}data-gathering option
  CHANGELOG.md
  src/js/lib/client/src/index.js
  src/js/lib/content/src/index.ts
  src/rust/ide/lib/args/src/lib.rs
Labels: Priority: Highest, Type: Bug, Category: GUI

#1832 Skip wasm testing packages that do not have wasm tests
  src/rust/test/Cargo.toml
  src/rust/test/src/bin/test_all.rs
Labels: Type: Enhancement, Category: Build System

#1838 Disable macOS notarizing
  src/js/lib/client/package.js
Labels: Category: Build System

#1755 Auto-layout when creating nodes
  CHANGELOG.md
  src/rust/Cargo.lock
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/view/Cargo.toml
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/src/debug_scenes/interface.rs
  src/rust/ide/view/src/project.rs
Labels: Type: Enhancement, Category: GUI

#1820 Avoid rounding errors in canvas resolution
  CHANGELOG.md
  src/rust/ensogl/lib/core/src/display/scene.rs
Labels: Category: BaseGL, Type: Bug

#1837 Fix code generation in the `enso-config` crate
  src/rust/lib/config/build.rs
  src/rust/lib/config/src/lib.rs
Labels: Priority: Highest, Category: Build System

#1815 Fix parsing of boolean command line options
  CHANGELOG.md
  src/js/lib/client/src/index.js
Labels: Priority: High, Type: Bug

#1845 Fix missing export of default port
  src/js/lib/common/src/server.js
Labels: Priority: Highest, Type: Bug, Category: GUI

#1776 Fix freezing after inactivity
  CHANGELOG.md
  src/rust/ensogl/lib/core/src/animation/physics/inertia.rs
  src/rust/ide/view/graph-editor/src/component/node/profiling.rs
  src/rust/ide/view/graph-editor/src/profiling.rs
Labels: Category: BaseGL, Type: Bug, Category: GUI
