Repository enso-org/ide, pull requests merged in 2021-08, with the labels that each got.

#1758 Fix performance issues in nodes' comments
  CHANGELOG.md
  src/rust/ensogl/lib/text/src/component/area.rs
  src/rust/ide/lib/ast/impl/src/crumbs.rs
  src/rust/ide/lib/ast/impl/src/lib.rs
  src/rust/ide/lib/ast/impl/src/macros.rs
  src/rust/ide/lib/parser/src/lib.rs
  src/rust/ide/lib/parser/tests/bugs.rs
  src/rust/ide/lib/parser/tests/crumbs.rs
  src/rust/ide/lib/parser/tests/macros.rs
  src/rust/ide/lib/parser/tests/parsing.rs
  src/rust/ide/lib/span-tree/src/action.rs
  src/rust/ide/lib/span-tree/src/generate.rs
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/project.rs
  src/rust/ide/src/controller/searcher.rs
  src/rust/ide/src/controller/searcher/action.rs
  src/rust/ide/src/controller/upload.rs
  src/rust/ide/src/double_representation.rs
  src/rust/ide/src/double_representation/alias_analysis.rs
  src/rust/ide/src/double_representation/alias_analysis/test_utils.rs
  src/rust/ide/src/double_representation/connection.rs
  src/rust/ide/src/double_representation/definition.rs
  src/rust/ide/src/double_representation/graph.rs
  src/rust/ide/src/double_representation/module.rs
  src/rust/ide/src/double_representation/node.rs
  src/rust/ide/src/double_representation/refactorings/collapse.rs
  src/rust/ide/src/ide/integration/file_system.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/node/output/area.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/src/debug_scenes/interface.rs
  src/rust/lib/frp/src/stream.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1762 Bump engine version to 0.2.21
  CHANGELOG.md
  src/js/lib/client/tasks/signArchives.js
  src/js/lib/project-manager/src/build.ts
  src/rust/ide/src/controller/project.rs
Labels: Difficulty: Intermediate, Priority: Highest, Type: Enhancement, Category: Controllers

#1742 Project Templates
  CHANGELOG.md
  build/paths.js
  build/run.js
  src/js/.gitignore
  src/js/lib/client/src/index.js
  src/js/lib/content/package.js
  src/js/lib/content/src/index.ts
  src/js/lib/content/src/project_manager.ts
  src/js/lib/content/src/style.css
  src/js/lib/content/src/templates-view.html
  src/js/lib/content/src/templates.ts
  src/js/lib/content/webpack.config.js
  src/rust/ide/lib/enso-protocol/src/project_manager.rs
  src/rust/ide/src/ide/initializer.rs
Labels: Difficulty: Core Contributor, Priority: High, Type: Enhancement, Category: GUI

#1767 Update window size
  src/js/lib/client/src/index.js
Labels: Difficulty: Core Contributor, Priority: High, Type: Enhancement, Category: GUI

#1770 Add TypeScript installation to CI.
  .github/workflows/gui-ci.yml
  build/workflow.js
Labels: Difficulty: Intermediate, Priority: Highest, Type: Bug, Category: Build System

#1769 Fixed build script on Windows.
  build/package.json
  build/run.js
Labels: Priority: Highest, Category: Build System

#1771 FRP with cycles
  src/rust/ensogl/lib/components/src/drop_down_menu.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/view/graph-editor/src/component/breadcrumbs/project_name.rs
  src/rust/ide/view/src/project.rs
  src/rust/ide/view/src/searcher.rs
  src/rust/ide/view/src/status_bar.rs
  src/rust/lib/frp/src/nodes.rs
  src/rust/lib/frp/src/stream.rs
Labels: Category: BaseGL, Difficulty: Hard, Priority: Highest, Type: Enhancement, Category: GUI

#1798 Bump engine to 0.2.24.
  CHANGELOG.md
  src/js/lib/client/tasks/signArchives.js
  src/js/lib/project-manager/src/build.ts
  src/rust/ide/src/controller/project.rs
Labels: Priority: Highest, Type: Enhancement

#1797 Add "All Search Result" category for showing filtering output.
  src/rust/ide/src/controller/searcher.rs
  src/rust/ide/src/controller/searcher/action.rs
  src/rust/ide/src/controller/searcher/action/hardcoded.rs
  src/rust/ide/src/ide/integration/project.rs
Labels: Difficulty: Intermediate, Priority: High, Type: Enhancement, Category: Controllers

#1779 Fix path to the module for the builtin dataflow error visualization.
  src/rust/ide/view/graph-editor/src/builtin/visualization/native/error.rs
Labels: Category: Visualizations

#1775 GeoMap: Ignore points with null coordinate values
  CHANGELOG.md
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/geoMap.js
Labels: Category: Visualizations

#1774 Fix the project CLI flag
  src/js/lib/content/src/index.ts
Labels: Priority: Medium, Type: Bug, Category: GUI

#1804 Visualization Fixes
  CHANGELOG.md
  src/rust/ensogl/lib/core/src/display/render/pass.rs
  src/rust/ensogl/lib/core/src/display/scene.rs
  src/rust/ide/lib/enso-protocol/src/language_server.rs
  src/rust/ide/lib/enso-protocol/src/language_server/constants.rs
  src/rust/ide/lib/enso-protocol/src/language_server/tests.rs
  src/rust/ide/lib/json-rpc/src/error.rs
  src/rust/ide/lib/json-rpc/src/lib.rs
  src/rust/ide/src/constants.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/view/graph-editor/src/lib.rs
Labels: Priority: Highest, Type: Enhancement, Category: Controllers

#1801 Bump Engine version to 0.2.26 and edition to 2021.14
  CHANGELOG.md
  src/js/lib/client/tasks/signArchives.js
  src/js/lib/project-manager/src/build.ts
  src/rust/ide/src/controller/project.rs
Labels: Difficulty: Core Contributor, Priority: Highest, Category: Build System, echoes/effort: S, echoes/intent: users/libraries, echoes/intent: technology/runtime

#1766 Fix docs loading stylesheet taking a lot of time, and update it to meet newest requirements
  build/package-lock.json
  src/js/lib/client/package-lock.json
  src/js/lib/content/src/docsStyle.css
  src/js/lib/content/src/docsStyle.less
  src/js/lib/content/src/index.html
  src/js/lib/content/webpack.config.js
  src/js/package-lock.json
  src/rust/ide/view/graph-editor/src/builtin/visualization/native/error.rs
  src/rust/ide/view/src/documentation.rs
  src/rust/ide/view/src/documentation/style.css
Labels: Difficulty: Core Contributor, Priority: High, Type: Enhancement, Category: GUI, echoes/effort: M, echoes/intent: technology/gui

#1761 Avoid error during initialization of histograms and scatterplots
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/histogram.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js
Labels: Priority: Highest, Type: Bug, Category: GUI, Category: Visualizations, Type: Regression

#1814 Update build script to separate builds for different targets and engine versions.
  build/paths.js
  build/run.js
  src/js/lib/project-manager/src/build.ts
Labels: Priority: Medium, Type: Bug, Category: Build System

#1817 Feature flag for visualization preview
  CHANGELOG.md
  src/rust/ide/view/graph-editor/src/component/node.rs
Labels: Type: Enhancement, Category: GUI
