Repository enso-org/ide, pull requests merged in 2021-03, with the labels that each got.

#1275 missing changelog updates + fixed link
  CHANGELOG.md
Labels: Category: Documentation, Priority: Highest, Type: Enhancement

#1279 Fix Main modules
  CHANGELOG.md
  src/rust/ide/src/constants.rs
  src/rust/ide/src/controller/searcher.rs
  src/rust/ide/src/controller/searcher/action.rs
  src/rust/ide/src/double_representation/module.rs
  src/rust/ide/src/model/module.rs
  src/rust/ide/src/model/suggestion_database/entry.rs
Labels: Category: Controllers, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1286 Engine 0.2.6
  CHANGELOG.md
  src/js/lib/project-manager/src/build.ts
  src/rust/ide/lib/ast/impl/src/crumbs.rs
  src/rust/ide/lib/ast/impl/src/lib.rs
  src/rust/ide/lib/parser/build.rs
  src/rust/ide/lib/parser/tests/bugs.rs
  src/rust/ide/lib/parser/tests/macros.rs
  src/rust/ide/lib/parser/tests/parsing.rs
  src/rust/ide/src/ide/initializer.rs
Labels: Category: Controllers, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1277 Update mixpanel integration to fix events beeing sent in invalid way.
  src/js/lib/content/src/index.js
  src/js/lib/content/webpack.config.js
  src/rust/ide/lib/analytics/src/data.rs
  src/rust/ide/lib/analytics/src/remote_log.rs
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/src/lib.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
Labels: Category: GUI, Difficulty: Intermediate, Type: Bug, Type: Enhancement

#1291 Allow visualizations to define context module for preprocessor
  CHANGELOG.md
  docs/product/visualizations.md
  src/rust/Cargo.lock
  src/rust/ide/Cargo.toml
  src/rust/ide/src/controller/graph/executed.rs
  src/rust/ide/src/controller/visualization.rs
  src/rust/ide/src/double_representation/identifier.rs
  src/rust/ide/src/double_representation/module.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/src/model/project.rs
  src/rust/ide/src/model/project/synchronized.rs
  src/rust/ide/view/graph-editor/Cargo.toml
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/geoMap.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/table.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/native/bubble_chart.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/native/error.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container.rs
  src/rust/ide/view/graph-editor/src/component/visualization/data.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/binding.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/definition.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/visualization.js
  src/rust/ide/view/graph-editor/src/component/visualization/instance.rs
  src/rust/ide/view/graph-editor/src/component/visualization/metadata.rs
  src/rust/ide/view/graph-editor/src/component/visualization/path.rs
  src/rust/ide/view/graph-editor/src/data.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/src/debug_scenes/visualization.rs
  src/rust/ide/view/src/documentation.rs
Labels: Category: Controllers, Category: Visualizations, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1314 Ensure correct port is used to connect to IDE server.
  CHANGELOG.md
  src/js/lib/client/src/index.js
  src/js/lib/common/src/server.js
Labels: Difficulty: Hard, Priority: High, Type: Bug

#1317 Avoid truncating pixel ratio for calculating cursor position on canvas.
  CHANGELOG.md
  src/rust/ensogl/lib/core/src/display/scene.rs
Labels: Category: BaseGL, Priority: Medium, Type: Bug

#1313 Do not crash the IDE when logging non-string objects.
  CHANGELOG.md
  src/js/lib/content/src/index.js
Labels: Category: GUI, Good First Issue, Priority: Medium, Type: Bug

#1312 Implement tooltips that show the type of an output port on hover.
  CHANGELOG.md
  src/rust/ensogl/lib/components/src/label.rs
  src/rust/ensogl/lib/components/src/lib.rs
  src/rust/ensogl/lib/core/src/animation/frp/animation.rs
  src/rust/ensogl/lib/core/src/animation/frp/animation/hysteretic.rs
  src/rust/ensogl/lib/core/src/data/color/data.rs
  src/rust/ensogl/lib/core/src/data/color/gradient.rs
  src/rust/ensogl/lib/core/src/display/scene.rs
  src/rust/ensogl/lib/core/src/display/shape/primitive/def/var.rs
  src/rust/ensogl/lib/core/src/gui.rs
  src/rust/ensogl/lib/core/src/gui/cursor.rs
  src/rust/ensogl/lib/core/src/gui/style.rs
  src/rust/ensogl/lib/text/src/component/area.rs
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/view/graph-editor/src/component.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/node/output/area.rs
  src/rust/ide/view/graph-editor/src/component/node/output/port.rs
  src/rust/ide/view/graph-editor/src/component/tooltip.rs
  src/rust/ide/view/graph-editor/src/lib.rs
Labels: Category: BaseGL, Category: GUI, Priority: Medium, Type: Enhancement

#1341 Catch syntax errors in custom visualisations
  CHANGELOG.md
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/definition.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/definition/function.rs
Labels: Category: GUI, Priority: High, Type: Bug

#1328 Add --no-data-gathering as a startup option
  CHANGELOG.md
  src/js/config.js
  src/js/lib/client/src/index.js
  src/js/lib/content/src/index.js
  src/js/lib/log-server/README.md
  src/js/lib/log-server/package.json
Labels: Priority: High, Type: Enhancement

#1353 Run all backend processed even if the IDE package is run with --no-window
  CHANGELOG.md
  src/js/lib/client/src/index.js
Labels: Category: GUI, Good First Issue, Priority: Medium, Type: Bug

#1357 Engine 0.2.8
  src/js/lib/project-manager/src/build.ts
  src/rust/ide/src/ide/initializer.rs
  src/rust/ide/src/model/execution_context.rs
  src/rust/ide/src/model/suggestion_database/example.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/geoMap.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/table.js
Labels: Category: Controllers, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#1348 Fix pasting multiline code in single-lined text area
  CHANGELOG.md
  src/rust/ensogl/lib/text/src/component/area.rs
Labels: Category: BaseGL, Priority: Highest, Type: Bug

#1332 Engine updates after adding node: send import first, then the new node
  CHANGELOG.md
  src/rust/ide/src/controller/searcher.rs
Labels: Category: Controllers, Priority: High, Type: Bug

#1358 Add a theming API for visualizations
  CHANGELOG.md
  docs/product/visualizations.md
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/binding.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/visualization.js
Labels: Category: Visualizations, Priority: Highest, Type: Enhancement

#1311 Scatterplot and Histogram: panning, pinching and RMB zooming works as expected.
  CHANGELOG.md
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/geoMap.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/histogram.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js
Labels: Category: Visualizations, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1335 Database Visualizations
  CHANGELOG.md
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/geoMap.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/sql.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/table.js
  src/rust/ide/view/graph-editor/src/component/visualization/registry.rs
Labels: Category: Visualizations, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1389 Hotfix: GeoMap not showing up in list
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/geoMap.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/sql.js
Labels: Category: Visualizations, Difficulty: Intermediate, Priority: Highest, Type: Regression

#1385 Fix strange this argument applying in searcher.
  CHANGELOG.md
  src/rust/ide/src/controller/searcher.rs
Labels: Category: Controllers, Good First Issue, Priority: Highest, Type: Bug

#1388 Update error visualization to work with latest engine
  src/rust/ide/view/graph-editor/src/builtin/visualization/native/error.rs
Labels: Category: Visualizations, Difficulty: Intermediate, Priority: Highest

#1393 Add Enso_Project.data entry to the searcher
  CHANGELOG.md
  src/rust/ide/src/controller/searcher.rs
  src/rust/ide/src/controller/searcher/action.rs
Labels: Category: Controllers, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#1377 Support Dataframes in Histogram and Scatter Plot Visualizations
  CHANGELOG.md
  docs/CONTRIBUTING.md
  docs/product/visualizations.md
  src/rust/ide/src/model/project/synchronized.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/helpers/number.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/histogram.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js
Labels: Category: Visualizations, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1355 Fullscreen Visualization
  CHANGELOG.md
  src/js/lib/content/src/style.css
  src/rust/ensogl/lib/core/src/display/object/class.rs
  src/rust/ensogl/lib/core/src/display/scene.rs
  src/rust/ensogl/lib/core/src/display/scene/dom.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/histogram.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/table.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/native/bubble_chart.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/native/error.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/native/raw_text.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container/action_bar.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container/fullscreen.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs
  src/rust/ide/view/graph-editor/src/component/visualization/instance.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/src/documentation.rs
  src/rust/ide/view/src/project.rs
Labels: Category: GUI, Category: Visualizations, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1384 Show visualization available for node output type only.
  CHANGELOG.md
  src/rust/ensogl/lib/components/src/drop_down_menu.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/geoMap.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/histogram.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/sql.js
  src/rust/ide/view/graph-editor/src/component/visualization/container.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container/action_bar.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
  src/rust/ide/view/graph-editor/src/component/visualization/registry.rs
  src/rust/ide/view/graph-editor/src/data.rs
  src/rust/ide/view/graph-editor/src/lib.rs
Labels: Category: GUI, Category: Visualizations, Difficulty: Intermediate, Priority: High, Type: Bug

#1409 Fix output port type when there are grey ports.
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/view/graph-editor/src/component/node/expression.rs
  src/rust/ide/view/graph-editor/src/component/node/output/area.rs
  src/rust/ide/view/src/debug_scenes/interface.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Intermediate, Priority: Highest, Type: Bug

#1363 Show visualization on output port hover.
  CHANGELOG.md
  src/rust/ensogl/lib/components/src/label.rs
  src/rust/ensogl/lib/core/src/animation/frp/animation.rs
  src/rust/ensogl/lib/core/src/animation/frp/animation/delayed.rs
  src/rust/ensogl/lib/core/src/display/scene.rs
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/native/error.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/native/raw_text.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/node/output/port.rs
  src/rust/ide/view/graph-editor/src/component/tooltip.rs
  src/rust/ide/view/graph-editor/src/component/visualization.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs
  src/rust/ide/view/graph-editor/src/component/visualization/instance.rs
  src/rust/ide/view/graph-editor/src/component/visualization/layer.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/lib/frp/src/nodes.rs
Labels: Category: GUI, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1383 `onHide` callback for Visualizations
  CHANGELOG.md
  docs/product/visualizations.md
  src/rust/ensogl/lib/core/src/display/object/class.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/definition.rs
  src/rust/ide/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs
Labels: Category: GUI, Category: Visualizations

#1395 Fix build failing when executing `run watch` on a clean build.
  CHANGELOG.md
  build/run.js
Labels: Category: Build System, Priority: Highest, Type: Bug

#1412 Show that visualization is selected
  CHANGELOG.md
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/view/graph-editor/src/component/visualization/container.rs
Labels: Category: GUI, Difficulty: Intermediate, Priority: Highest, Type: Enhancement
