Repository enso-org/ide, pull requests merged in 2021-06, with the labels that each got.

#1587 Opening Projects in IDE
  CHANGELOG.md
  docs/product/shortcuts.md
  src/rust/ide/lib/enso-protocol/src/lib.rs
  src/rust/ide/src/controller/ide.rs
  src/rust/ide/src/controller/ide/desktop.rs
  src/rust/ide/src/controller/searcher.rs
  src/rust/ide/src/controller/searcher/action.rs
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/view/src/project.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1593 Drop Manager in ensogl
  src/rust/Cargo.lock
  src/rust/Cargo.toml
  src/rust/ensogl/example/Cargo.toml
  src/rust/ensogl/example/src/drop_manager.rs
  src/rust/ensogl/example/src/lib.rs
  src/rust/ensogl/lib/web/Cargo.toml
  src/rust/ensogl/lib/web/src/drop.rs
  src/rust/ensogl/lib/web/src/lib.rs
  src/rust/lib/system/web/Cargo.toml
  src/rust/lib/system/web/src/lib.rs
  src/rust/lib/system/web/src/stream.rs
Labels: Category: BaseGL, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1366 Enable build signing for macOS and Windows binaries.
  .github/workflows/gui-ci.yml
  CHANGELOG.md
  build/package-lock.json
  build/workflow.js
  package-lock.json
  src/js/lib/client/entitlements.mac.plist
  src/js/lib/client/package.js
  src/js/lib/client/tasks/notarize.js
  src/js/lib/client/tasks/signArchives.js
  src/js/package-lock.json
Labels: Category: Build System, Difficulty: Hard, Priority: High, Type: Enhancement

#1546 Add profiling mode to GUI
  CHANGELOG.md
  docs/product/shortcuts.md
  src/rust/Cargo.lock
  src/rust/ensogl/lib/components/src/toggle_button.rs
  src/rust/ensogl/lib/core/src/data/color/space/def.rs
  src/rust/ensogl/lib/core/src/display/object/class.rs
  src/rust/ensogl/lib/core/src/display/scene/dom.rs
  src/rust/ensogl/lib/core/src/display/shape/primitive/def/primitive.rs
  src/rust/ensogl/lib/text/src/component.rs
  src/rust/ensogl/lib/text/src/component/area.rs
  src/rust/ensogl/lib/text/src/component/selection.rs
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/view/graph-editor/Cargo.toml
  src/rust/ide/view/graph-editor/src/component.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/node/input/area.rs
  src/rust/ide/view/graph-editor/src/component/node/output/area.rs
  src/rust/ide/view/graph-editor/src/component/node/output/port.rs
  src/rust/ide/view/graph-editor/src/component/node/profiling.rs
  src/rust/ide/view/graph-editor/src/component/profiling.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/graph-editor/src/profiling.rs
  src/rust/ide/view/graph-editor/src/view.rs
  src/rust/ide/view/src/debug_scenes/interface.rs
  src/rust/lib/frp/src/nodes.rs
Labels: Category: GUI, Priority: Medium, Type: Enhancement

#1620 Fix shape ordering
  src/rust/ide/view/graph-editor/src/component/breadcrumbs.rs
  src/rust/ide/view/graph-editor/src/component/breadcrumbs/project_name.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
Labels: Category: GUI, Good First Issue, Priority: Highest, Type: Bug

#1588 Implement area selection.
  CHANGELOG.md
  src/rust/ensogl/lib/core/src/gui/cursor.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/node/action_bar.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/graph-editor/src/selection.rs
  src/rust/ide/view/graph-editor/src/selection/bounding_box.rs
Labels: Category: GUI, Difficulty: Hard, Priority: High, Type: Enhancement

#1629 A quickfix for visual artifacts in nodes.
  .github/workflows/gui-ci.yml
  src/rust/ide/view/graph-editor/src/component/node.rs
Labels: Category: GUI, Difficulty: Intermediate, Priority: Highest, Type: Bug

#1637 Alive Message to Mixpanel with flag
  src/js/lib/content/src/index.ts
  src/rust/ide/src/ide.rs
Labels: Category: Controllers, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#1639 Prompt Message
  src/rust/ensogl/lib/core/src/display/scene.rs
  src/rust/ensogl/lib/text/src/component/area.rs
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/view/src/debug_scenes/interface.rs
  src/rust/ide/view/src/project.rs
Labels: Category: GUI, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#1619 Uploading files
  src/rust/Cargo.lock
  src/rust/ensogl/example/src/drop_manager.rs
  src/rust/ensogl/lib/web/src/drop.rs
  src/rust/ide/Cargo.toml
  src/rust/ide/lib/enso-protocol/build.rs
  src/rust/ide/lib/enso-protocol/src/binary/client.rs
  src/rust/ide/lib/enso-protocol/src/binary/message.rs
  src/rust/ide/lib/enso-protocol/src/binary/serialization.rs
  src/rust/ide/lib/enso-protocol/src/common/error.rs
  src/rust/ide/lib/enso-protocol/src/generated/binary_protocol_generated.rs
  src/rust/ide/lib/enso-protocol/src/language_server.rs
  src/rust/ide/lib/enso-protocol/src/language_server/response.rs
  src/rust/ide/lib/enso-protocol/src/language_server/types.rs
  src/rust/ide/lib/enso-protocol/src/lib.rs
  src/rust/ide/lib/enso-protocol/src/types.rs
  src/rust/ide/lib/json-rpc/src/error.rs
  src/rust/ide/lib/json-rpc/src/messages.rs
  src/rust/ide/lib/utils/src/serde.rs
  src/rust/ide/src/controller.rs
  src/rust/ide/src/controller/graph.rs
  src/rust/ide/src/controller/graph/executed.rs
  src/rust/ide/src/controller/searcher.rs
  src/rust/ide/src/controller/upload.rs
  src/rust/ide/src/ide/integration/project.rs
  src/rust/ide/src/lib.rs
  src/rust/ide/src/model/module.rs
  src/rust/ide/src/model/module/synchronized.rs
  src/rust/ide/src/model/project.rs
  src/rust/ide/src/model/undo_redo.rs
  src/rust/ide/src/notification.rs
  src/rust/ide/src/test.rs
  src/rust/ide/src/tests.rs
  src/rust/ide/view/graph-editor/Cargo.toml
  src/rust/ide/view/graph-editor/src/component/breadcrumbs/breadcrumb.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/lib/system/web/src/lib.rs
Labels: Category: Controllers, Category: GUI, Difficulty: Hard, Priority: High, Type: Enhancement

#1640 Update API to support the new content roots
  src/js/lib/client/tasks/signArchives.js
  src/js/lib/project-manager/src/build.ts
  src/rust/ide/lib/enso-protocol/src/language_server/connection.rs
  src/rust/ide/lib/enso-protocol/src/language_server/response.rs
  src/rust/ide/lib/enso-protocol/src/language_server/tests.rs
  src/rust/ide/lib/enso-protocol/src/language_server/types.rs
  src/rust/ide/src/controller/project.rs
  src/rust/ide/src/controller/visualization.rs
  src/rust/ide/src/ide.rs
  src/rust/ide/src/model/project.rs
  src/rust/ide/src/model/project/synchronized.rs
  src/rust/ide/tests/language_server.rs
Labels: Category: Controllers, Difficulty: Hard, Priority: High, Type: Enhancement

#1628 Fix node action eye icon not appearing on hover.
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/node/action_bar.rs
Labels: Category: GUI, Difficulty: Intermediate, Priority: Highest, Type: Bug

#1633 Fix regression that prohibits multiple nodes from being moved.
  src/rust/ide/view/graph-editor/src/selection.rs
Labels: Category: GUI, Priority: Highest, Type: Regression
