Repository enso-org/ide, pull requests merged in 2021-04, with the labels that each got.

#1413 Fix Nested Macros Deserialization
  CHANGELOG.md
  src/rust/ide/lib/parser/Cargo.toml
  src/rust/ide/lib/parser/src/jsclient.rs
  src/rust/ide/lib/parser/src/lib.rs
  src/rust/ide/lib/parser/src/wsclient.rs
  src/rust/ide/lib/parser/tests/parsing.rs
Labels: Category: Controllers, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#1428 Fix Backend Dying
  CHANGELOG.md
  src/js/lib/client/src/index.js
Labels: Category: GUI, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#1442 Fix visualization displayed with error on preview
  src/rust/ide/view/graph-editor/src/component/node.rs
Labels: Category: GUI, Difficulty: Intermediate, Priority: Highest, Type: Bug

#1448 Engine 0.2.10
  src/js/lib/project-manager/src/build.ts
  src/rust/ide/lib/enso-protocol/src/language_server/types.rs
  src/rust/ide/src/ide/initializer.rs
  src/rust/ide/src/model/suggestion_database.rs
  src/rust/ide/src/model/suggestion_database/entry.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script.rs
  src/rust/ide/view/graph-editor/src/builtin/visualization/java_script/geoMap.js
Labels: Category: Controllers, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1449 fix code editor theme
  src/rust/ensogl/lib/text/src/component/area.rs
  src/rust/ide/view/src/code_editor.rs
  src/rust/ide/view/src/project.rs
Labels: Category: GUI, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1445 Suppressing spurious type updates.
  CHANGELOG.md
  src/rust/ide/src/ide/integration.rs
  src/rust/ide/view/graph-editor/src/component/node/input/port.rs
  src/rust/ide/view/graph-editor/src/component/type_coloring.rs
  src/rust/ide/view/graph-editor/src/lib.rs
Labels: Category: GUI, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1457 Added background to error visualization under node
  src/rust/ide/view/graph-editor/src/component/node.rs
  src/rust/ide/view/graph-editor/src/component/node/error.rs
Labels: Category: GUI, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1469 Fix non-selectable crumbs
  src/rust/ide/view/graph-editor/src/component/breadcrumbs.rs
  src/rust/ide/view/graph-editor/src/component/breadcrumbs/breadcrumb.rs
Labels: Category: GUI, Good First Issue, Priority: Highest, Type: Bug

#1470 Point users to the Enso repo
  CHANGELOG.md
  README.md
Labels: Category: Documentation, Priority: Highest, Type: Enhancement

#1510 Update Enso Reference to new Tailwind-Generated stylesheet.
  src/rust/ide/lib/parser/build.rs
  src/rust/ide/lib/parser/tests/bugs.rs
  src/rust/ide/lib/parser/tests/doc-gen.rs
  src/rust/ide/view/src/documentation.rs
  src/rust/ide/view/src/documentation/style.css
Labels: Category: GUI, Category: Visualizations, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1520 Fix adding gzip encoding only for .gz ended files
  .github/workflows/gui-ci.yml
  build/workflow.js
Labels: Category: Build System, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1511 Close and Fullscreen buttons for IDE in the cloud
  CHANGELOG.md
  src/js/lib/client/src/index.js
  src/js/lib/content/src/index.js
  src/rust/Cargo.lock
  src/rust/ensogl/example/src/lib.rs
  src/rust/ensogl/example/src/mouse_events.rs
  src/rust/ensogl/lib/core/src/data/color/data.rs
  src/rust/ensogl/lib/core/src/data/color/space/conversion.rs
  src/rust/ensogl/lib/core/src/data/color/space/def.rs
  src/rust/ensogl/lib/core/src/display/shape/primitive/def/var.rs
  src/rust/ensogl/lib/core/src/display/shape/primitive/style_watch.rs
  src/rust/ensogl/lib/core/src/display/style/sheet.rs
  src/rust/ensogl/lib/core/src/system/gpu/shader/glsl.rs
  src/rust/ensogl/lib/theme/src/lib.rs
  src/rust/ide/lib/args/src/lib.rs
  src/rust/ide/view/Cargo.toml
  src/rust/ide/view/graph-editor/src/component/breadcrumbs.rs
  src/rust/ide/view/graph-editor/src/component/breadcrumbs/project_name.rs
  src/rust/ide/view/graph-editor/src/lib.rs
  src/rust/ide/view/src/lib.rs
  src/rust/ide/view/src/project.rs
  src/rust/ide/view/src/window_control_buttons.rs
  src/rust/ide/view/src/window_control_buttons/close.rs
  src/rust/ide/view/src/window_control_buttons/common.rs
  src/rust/ide/view/src/window_control_buttons/fullscreen.rs
  src/rust/lib/frp/src/nodes.rs
  src/rust/lib/system/web/src/lib.rs
  src/rust/lib/types/src/algebra.rs
  src/rust/lib/types/src/topology.rs
Labels: Category: GUI, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1535 Update changelog parser to respect rc
  build/release.js
Labels: Category: Build System, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement
